### ISSUE TITLE
Presets.yaml unsupported

### ISSUE THREAD

**Issue by whitevamp** [phamhungd/WC-SDVN#1]
when running a NSFW wildcard tag i get this error.

`Wildcard file C:\AI_Generation\stable-diffusion-webui-master\extensions\sd-dynamic-prompts\wildcards\sdvnWildcards_v10\WC-SDVN\2000Wildcards\Presets.yaml has unsupported value for key NSFW, monocolored, monochrome, (line-art), masterpiece, best quality, from above, hetero, naked, ((1boy) and (penis) and (on back) and (lying) and (muscular)), ((1girl) with (pussy) and (on back) and (lying) and and (spread legs) and (nipples) and (<[Age][Female][Adult]>)), ((sex) and (vaginal)), (shiny skin:1.2)), (Junji Ito:1.21), (carne griffiths:1.21), (WLOP:1.21)**, futanari,  armpit hair, full color, color**/Description`

and looking at Presets.yaml [LN#136](https://github.com/phamhungd/WC-SDVN/blob/0356c64780bf6c3013e4af92927ce100a093eeba/2000/Presets.yaml#L136) im not seeing any thing that glaringly sticks out to me. granted I am new to wildcards extension, and the format for yaml files.
```
'NSFW, monocolored, monochrome, (line-art), masterpiece, best quality, from above, hetero, naked, ((1boy) and (penis) and (on back) and (lying) and (muscular)), ((1girl) with (pussy) and (on back) and (lying) and and (spread legs) and (nipples) and (<[Age][Female][Adult]>)), ((sex) and (vaginal)), (shiny skin:1.2)), (Junji Ito:1.21), (carne griffiths:1.21), (WLOP:1.21)**, futanari,  armpit hair, full color, color**':
 Description:
 Tags:
  - Preset
  - Female
  - Futanari
  - NSFW
  - Sex Prompt
  - Missionary
  - Doujinshi
```

**Comment by phamhungd** [comment]
you should ignore these messages, it doesn't affect anything
